### ISSUE TITLE
tracetcp fails, won't even get past first hop

### ISSUE THREAD

**Issue by jtryon81** [0xcafed00d/tracetcp#3]
We have a vendor trying to use this utility and while a regular traceroute works, tracetcp doesn't over any port that I've tried.  I can traceroute to 66.55.43.151 which is the site he's trying to tracetcp to, and can ping but can't use your utility to get there.  All I get are timeouts, so it's not even getting past the first hop.  This is on a Cisco-based network; are there any router functions that have to be turned off for your tool to work?  I've exhausted every option that I can think of.  There's no ACL blocking it, nothing of that sort that I can tell.

Thanks in advance!

**Comment by 0xcafed00d** [comment]
try 1.0.1
