### ISSUE TITLE
Doesn't close connection cleanly

### ISSUE THREAD

**Issue by ravenstar68** [0xcafed00d/tracetcp#6]
When tracetcp connects to the target destination it appears to finish after the destination sends a SYN, ACK back without actually closing the connection properly.

Wouldn't it be better to close the connection cleanly with an RST or even and ACK and FIN when done?  
As it stands the destination tries sending back a couple of extra SYN,ACKS when it gets no reply.

**Comment by LegacyOne** [comment]
Maybe but then I'm sure some RFC lists a possible condition where you send a SYN and you crash the other end sends a SYN ACK but you have crashed so its got to be down to the other end that received the SYN as to what to do.

As a side note its interesting if you do.
tracetcp grc.com 
Destination Reached in 154 ms. Port closed on 4.79.142.200
yet how can it be closed and send a RST ACK yet you can get to GRC is down to the current SYN being sent by tracetcp which adding TCP options  maximum segment size solves.

**Comment by 0xcafed00d** [comment]
Leaving the connection half open for a few seconds really does no harm to the remote host, as it will receive only 1 syn packet from tracetcp. There is no need to change this behaviour.
