### ISSUE TITLE
Winpcap NDIS6

### ISSUE THREAD

**Issue by ion-storm** [0xcafed00d/tracetcp#7]
I tried using this with Windows 10 with the newer NDIS6 http://www.win10pcap.org/ driver and it did not work, can you confirm that this works?
Thanks

**Comment by 0xcafed00d** [comment]
No it doesn't work. currently only the winpcap from here:  http://www.winpcap.org/   is supported, and works on windows 10

**Comment by hsluoyz** [comment]
Hi.

You would like to try Npcap: https://github.com/nmap/npcap.

It's another fork of WinPcap with multiple new features.

**Comment by simulatedsimian** [comment]
its doesn't work for me. if it works for you that's great, if not please use the supported winpcap from here: http://www.winpcap.org/ is supported, and works on windows 10.

I'm afraid i don't have the resources to support all the different variations of packet capture libs. If you would like to debug the problem, and submit a pull request, I would be happy to merge it.
