### ISSUE TITLE
Windows 10 support?

### ISSUE THREAD

**Issue by jlpetz** [0xcafed00d/tracetcp#8]
I ran this on Windows 10(from both Powersheel and command prompt). But the output is showing the trace as never completing and every hope is timing out. 

I know I have connectivity though as a telnet to the relevant TCP port connects and tracert/ping also return.

Is it just me or is the utility not working for Windows 10?

I have Wireshark 2.0.4 which I think comes with WinPCAP 4.1.3

**Comment by 0xcafed00d** [comment]
Every Windows 10 Machine I've tried tracetcp on worked fine. Occasionally i get reports of tracetcp not working on various versions of windows (xp, vista, 7, 8, & 10) i've not so managed to find any commonality to these reports. 

Are you using wireless? if so try a wired connection on the same network, also try https://github.com/nmap/npcap  as an alternative to winpcap, which has specific windows 10 support, it may help, it may not.

**Comment by hsluoyz** [comment]
Hi @jlpetz ,

Please try Npcap installer at:
https://github.com/nmap/npcap/releases

Npcap is an update of WinPcap to NDIS 6 Light-Weight Filter (LWF) technique. It supports Windows Vista, 7, 8 and 10. It is sponsored by the Nmap Project.
